describe('teste site da automate exercise', () => {
  before('entrar no site da automate exercise', () => {
    cy.visit('https://automationexercise.com/login')
  })
 
  it('cadastrar um cliente no site da automate exercise', () => {
    // cy.visit('https://automationexercise.com/login')
    cy.get('[data-qa="signup-name"]')
    .click()
    .type('Gabriela')
    cy.get('[data-qa="signup-email"]')
    .click()
    .type('gabriela.teste@gmail.com')
    cy.get('[data-qa="signup-button"]')
    .click()
    cy.wait('5000')
    cy.get('#id_gender1')
    .click()
    cy.get('[data-qa="password"]')
    .click()
    .type('teste2023')
    cy.get('#newsletter')
    .click()
    cy.get('[data-qa="first_name"]')
    .click()
    .type('Gabriela')
    cy.get('[data-qa="last_name"]')
    .click()
    .type('Silvestre Sanchez')
    cy.get('[data-qa="company"]')
    .click()
    .type ('Teste')
    cy.get('[data-qa="address"]')
    .click()
    .type ('Rua teste')
    cy.get('[data-qa="address2"]')
    .click()
    .type('Rua teste II')
    cy.get('[data-qa="state"]')
    .click()
    .type("Estados dos Testes")
    cy.get('[data-qa="city"]')
    .click()
    .type('Teste City')
    cy.get('[data-qa="zipcode"]')
    .click()
    .type('22')
    cy.get('[data-qa="mobile_number"]')
    .click()
    .type('22-99999-9999')
    cy.get('[data-qa="create-account"]')
    .click()
    cy.get('[data-qa="continue-button"]')
    .click()
  })

})