name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.17.1'

      - name: Install dependencies
        run: npm install

      - name: Fix Cypress permissions
        run: sudo chmod +x ./node_modules/.bin/cypress

      - name: Run tests
        run: npx cypress run
