name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Install Cypress binary
        run: npx cypress install

      - name: Fix permissions for Cypress
        run: chmod +x node_modules/.bin/cypress

      - name: Run Cypress tests
        run: npx cypress run

      - name: Generate Allure Report
        run: npm run allure

      - name: Upload Allure Report
        uses: actions/upload-artifact@v3  # Atualizado para v3
        with:
          name: allure-report
          path: allure-report

      - name: Upload Cypress screenshots
        uses: actions/upload-artifact@v3  # Atualizado para v3
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      - name: Upload Cypress videos
        uses: actions/upload-artifact@v3  # Atualizado para v3
        with:
          name: cypress-videos
          path: cypress/videos
