name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.17.1'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: |
          sudo chown -R $USER:$USER ./node_modules
          sudo chmod -R 755 ./node_modules/.bin
          npx cypress run
